title: 欢迎使用
subtitle: 个人导航站点

# 指定使用的模板文件名，现有页面模板可见templates\pages
template: home

categories:
  - name: 来我的网站看看吧
    icon: fas fa-house-user
    sites:
      - name: LivreTV
        url: https://qingjue-tv.pages.dev/
        icon: fas fa-tv
        description: 免费在线视频搜索与观看平台
      - name: NodeCrypt
        url: https://nodecrypt1.qingjue723.workers.dev/
        icon: fas fa-comments
        description: 端到端加密的安全网页聊天
      - name: CloudPaste
        url: https://cloudpaste-frontend-2yc.pages.dev/
        icon: fas fa-file-lines
        description: 在线文本/大文件分享平台
      - name: 密码管理器
        url: https://password-manager.qingjue723.workers.dev/
        icon: fas fa-key
        description: 安全的密码存储/智能填充/云备份同步
      - name: 图床
        url: https://cloudflare-imgbed-6fi.pages.dev/
        icon: fas fa-images
        description: 用来保管要插入博文的图片/视频/音频等
  - name: 来用AI
    icon: fas fa-robot
    sites:
      - name: ChatGPT
        url: https://chatgpt.com/
        icon: fas fa-robot
        description: G老师说话最好听
      - name: Gemini
        url: https://gemini.google.com/app
        icon: fas fa-robot
        description: 最好用的哈基米
      - name: Google AI Studio
        url: https://aistudio.google.com/prompts/new_chat
        icon: fas fa-robot
        description: 最好用的哈基米专业版
      - name: 大模型竞技场
        url: https://lmarena.ai/
        icon: fas fa-scale-balanced
        description: 大模型的试用/评分/排名
      - name: DeepSeek
        url: https://chat.deepseek.com/
        icon: fas fa-robot
        description: 中文很好的小鲸鱼
      - name: Claude
        url: https://claude.ai/recents
        icon: fas fa-robot
        description: 写代码很厉害 但是免费额度不够用呀
      - name: Grok
        url: https://grok.com/chat
        icon: fas fa-robot
        description: 没有审核 可以搞黄
      - name: RawChat公益站点
        url: https://sharedchat.fun/
        icon: fas fa-robot
        description: 第三方Gpt公益站
      - name: Deep Ask 深思所问
        url: https://deepask.cc/
        icon: fas fa-robot
        description: 第三方各种模型站点
      - name: NotebookLM
        url: https://notebooklm.google.com/
        icon: fas fa-book-open-reader
        description: 在线知识库，访谈功能惊艳
  - name: 一些常用的网站
    icon: fas fa-wrench
    sites:
      - name: Linux Do
        url: https://linux.do/
        icon: fab fa-linux
        description: 有关AI、开发、羊毛的社区
      - name: Github
        url: https://github.com/
        icon: fab fa-github
        description: 忙忙碌碌寻宝藏
      - name: Cloudflare
        url: https://dash.cloudflare.com
        icon: fab fa-cloudflare
        description: 感谢有你温暖了四季
      - name: Bilibili
        url: https://www.bilibili.com/
        icon: fab fa-bilibili
        description: 知名学习网站
      - name: Youtube
        url: https://www.youtube.com/
        icon: fab fa-youtube
        description: 知名学习网站二号
