title: 软件下载
subtitle: 这里是我的装机必备软件的下载页面

# 指定使用的模板文件名，现有页面模板可见templates\pages
template: projects

categories:
  - name: 文件与系统工具
    icon: fas fa-cogs
    sites:
      - name: OneCommander
        icon: fas fa-folder-open
        description: 高颜值多功能文件管理器，支持双栏/标签/层级导航，免费版够用
        url: https://www.onecommander.com/
      - name: Everything
        icon: fas fa-search
        description: 极速本地文件搜索神器，瞬间查找电脑内任何文件或文件夹
        url: https://www.voidtools.com/zh-cn/
      - name: ReNamer Pro
        icon: fas fa-pencil-alt
        description: 强大的批量文件重命名工具，支持复杂规则，轻松搞定海量文件改名
        url: https://4fb.cn/soft/pc/2456.html
      - name: 7zip
        icon: fas fa-file-archive
        description: 免费开源的文件压缩神器，压缩比高，轻量强大，装机必备
        url: https://7-zip.org/
      - name: 酷呆桌面
        icon: fas fa-desktop
        description: 高效桌面整理工具，分区归类图标和文件，让桌面告别杂乱
        url: https://www.coodesker.com/purchase
      - name: HiBit Uninstaller
        icon: fas fa-trash-alt
        description: 功能全面的免费卸载工具，彻底清除软件残留，还集成多种系统工具
        url: https://www.hibitsoft.ir/Uninstaller.html
      - name: 图吧工具箱
        icon: fas fa-toolbox
        description: 硬件检测与系统维护工具合集，绿色开源，DIY玩家必备
        url: https://www.tbtool.cn/
      - name: PixPin
        icon: fas fa-crop-alt
        description: 全能截图工具，集截图/贴图/长截图/OCR/标注于一体，轻巧高效
        url: https://pixpin.cn/
      - name: 按键精灵
        icon: fas fa-robot
        description: 模拟键鼠操作的自动化软件，录制或编写脚本，解放双手
        url: https://download.myanjian.com/
      - name: QtScrcpy
        icon: fas fa-mobile-alt
        description: 安卓投屏与控制工具，支持键鼠操作，界面友好功能丰富
        url: https://github.com/barry-ran/QtScrcpy/releases
      - name: 小狼毫输入法
        icon: fas fa-keyboard
        description: 开源输入法框架RIME，高度可定制，注重隐私不联网
        url: https://rime.im/download/
      - name: Enpass
        icon: fas fa-key
        description: 安全的跨平台密码管理器，数据离线存储，可自选云服务同步
        url: https://www.enpass.io/downloads/

  - name: 文档与创作
    icon: fas fa-file-alt
    sites:
      - name: Office
        icon: fas fa-file-word
        description: 全球最主流的办公套件，文档/表格/演示制作必备
        url: https://otp.landian.vip/zh-cn/download.html
      - name: 腾讯文档
        icon: fas fa-users
        description: 支持多人实时协作的在线文档，高效团队办公利器
        url: https://docs.qq.com/home#download
      - name: Notion
        icon: fas fa-book-open
        description: 笔记、知识库与任务管理 All-in-One 协作平台，灵活强大
        url: https://www.notion.com/zh-cn/desktop
      - name: 好用便签
        icon: fas fa-sticky-note
        description: 简洁实用的桌面便签，随手记录待办与灵感
        url: https://www.haoyong333.com/downloadCenter.html
      - name: PDF-XChange Editor
        icon: fas fa-file-pdf
        description: 功能强大的PDF查看与编辑器，支持OCR、页面操作等高级功能
        url: https://4fb.cn/soft/pc/1753.html
      - name: MinerU
        icon: fas fa-microscope
        description: 开源PDF解析工具，精准提取文本/表格/公式，转换为MD/JSON格式
        url: https://github.com/opendatalab/MinerU
      - name: Calibre
        icon: fas fa-book-reader
        description: 强大开源的电子书管理中心，集阅读/转换/整理于一体
        url: https://calibre-ebook.com/download_windows
      - name: EBWin4
        icon: fas fa-spell-check
        description: 支持多种格式的本地电子词典，离线查词，语言学习好帮手
        url: https://www.vector.co.jp/download/file/winnt/writing/fh772378.html
      - name: Cherry Studio
        icon: fas fa-brain
        description: 一站式AI助手平台，聚合多模型对话/知识库/AI绘画/翻译
        url: https://www.cherry-ai.com/download
      - name: OBS Studio
        icon: fas fa-video
        description: 免费开源的视频录制与直播推流软件，专业强大，主播必备
        url: https://obsproject.com/
      - name: Buzz
        icon: fas fa-microphone-alt
        description: 基于Whisper的音频转字幕工具，实时转录，支持离线运行
        url: https://github.com/chidiwilliams/buzz/releases
      - name: MSST WebUI
        icon: fas fa-volume-up
        description: 基于VITS的语音合成WebUI，轻松生成高质量AI语音
        url: https://github.com/SUC-DriverOld/MSST-WebUI/releases

  - name: 网络与通讯
    icon: fas fa-globe-asia
    sites:
      - name: 微信
        icon: fab fa-weixin
        description: 不得不用的社交软件
        url: https://weixin.qq.com/
      - name: QQ
        icon: fab fa-qq
        description: 不得不用的社交软件
        url: https://im.qq.com/index/
      - name: YY
        icon: fas fa-microphone
        description: 不得不用的语音软件
        url: https://www.yy.com/pcyy/
      - name: TeamSpeak 3
        icon: fas fa-headset
        description: 专业语音通信软件，低占用高音质，游戏开黑首选
        url: https://teamspeak.com/zh-CN/downloads/#ts3client
      - name: Internet Download Manager
        icon: fas fa-download
        description: 经典多线程下载神器IDM，支持断点续传与视频嗅探
        url: https://www.internetdownloadmanager.com/download.html
      - name: 文件蜈蚣
        icon: fas fa-angle-double-down
        description: 开源全能下载管理器，支持HTTP/BT/磁力链等多种协议
        url: https://www.filecxx.com/zh_CN/
      - name: 百度网盘
        icon: fas fa-cloud-download-alt
        description: 不得不用的网盘
        url: https://pan.baidu.com/download#win
      - name: 夸克网盘
        icon: fas fa-cloud
        description: 88VIP送的网盘
        url: https://pan.quark.cn/
      - name: 123云盘
        icon: fas fa-share-square
        description: 123云盘
        url: https://www.123pan.com/Downloadclient
      - name: 阿里云盘
        icon: fas fa-rocket
        description: 阿里云盘
        url: https://www.alipan.com/
      - name: LocalSend
        icon: fas fa-wifi
        description: 免费开源的局域网文件快传工具，无需联网，安全高速
        url: https://github.com/localsend/localsend/releases
      - name: FlClash
        icon: fas fa-paper-plane
        description: 基于ClashMeta的多平台代理客户端，支持WebDAV
        url: https://github.com/chen08209/FlClash/releases
      - name: SubsCheck
        icon: fas fa-network-wired
        description: 机场订阅链接检查与管理工具，可测速、查流量、转格式
        url: https://github.com/cmliu/SubsCheck-Win-GUI/releases

  - name: 影音与娱乐
    icon: fas fa-photo-video
    sites:
      - name: PotPlayer
        icon: fas fa-play-circle
        description: 强大的全能视频播放器，内置解码器，性能优秀，自定义选项丰富
        url: https://potplayer.daum.net/?lang=zh_CN
      - name: Honeyview
        icon: fas fa-image
        description: 轻量快速的图片浏览器，支持RAW格式，可直接看压缩包内图片
        url: https://www.bandisoft.com/honeyview/
      - name: 洛雪音乐
        icon: fas fa-music
        description: 开源桌面音乐播放器，聚合多平台音源，界面简洁美观
        url: https://github.com/lyswhut/lx-music-desktop/releases
      - name: 网易云
        icon: fas fa-headphones-alt
        description: 以歌单、评论和个性化推荐为特色的音乐社区
        url: https://music.163.com/#/download
      - name: Simple Live
        icon: fas fa-tv
        description: 多直播平台聚合观看工具，免登录看B站/斗鱼/虎牙/抖音
        url: https://github.com/xiaoyaocz/dart_simple_live/releases
      - name: Steam
        icon: fab fa-steam
        description: 全球最大的PC游戏数字发行平台，集商店/社交/创意工坊于一体
        url: https://store.steampowered.com/about/
      - name: BongoCat
        icon: fas fa-cat
        description: 可爱的桌面萌宠，实时映射键鼠操作，直播录屏增添趣味
        url: https://github.com/ayangweb/BongoCat/releases
