# 网站基本信息
title: "清绝导航站"
description: "个人收藏的网站导航页"
keywords: "导航,网址,书签,个人主页"

# 个人资料配置
profile:
  title: "> Qingjue"
  subtitle: "Executing Navigation Sequence..."
  description: "一个个人导航站。// My Entry Point"

# 主题和样式设置
theme:
  default: "light"
  toggleIcon: true
  
# 字体配置
fonts:
  title: "Roboto, sans-serif"
  content: "Noto Sans SC, sans-serif"
  
# 社交媒体链接
social:
  - name: "Bilibili"
    url: "https://space.bilibili.com/4296615"
    icon: "fa-brands fa-bilibili"
