# 网站基本信息
title: "清绝个人导航"
description: "个人收藏的网站导航页"
keywords: "导航,网址,书签,个人主页"

# 个人资料配置
profile:
  title: "Hello,"
  subtitle: "Welcome to My Navigation"
  description: "这是清绝的个人导航页面"

# 主题和样式设置
theme:
  default: "light"
  toggleIcon: true
  
# 字体配置
fonts:
  title: "Roboto, sans-serif"
  content: "Noto Sans SC, sans-serif"
  
# 社交媒体链接
social:
  - name: "Bilibili"
    url: "https://space.bilibili.com/4296615"
    icon: "fa-brands fa-bilibili"
