# 网站基本信息
title: "清绝的导航站"                      
description: "个人收藏的网站导航页"
keywords: "导航,网址,书签,个人主页"

# 个人资料配置
profile:
  title: "Stargate Engaged"
  subtitle: "坐标锁定 // Coordinate Locked"
  description: "正在跃迁至下一个目的地..."

# 主题和样式设置
theme:
  default: "light"
  toggleIcon: true
  
# 字体设置
fonts:
  title:  # 标题字体设置
    family: "Source Han Sans CN"  # 字体名称
    weight: 500       # 字重值：400常规、500中等、700粗体
    source: "google"  # 字体来源：google或system
  subtitle:  # 副标题字体
    family: "Source Han Sans CN"
    weight: 700
    source: "google"
  body:  # 正文字体
    family: "Source Han Sans CN"
    weight: 400
    source: "google"
  
# 社交媒体链接
social:
  - name: "Bilibili"
    url: "https://space.bilibili.com/4296615"
    icon: "fa-brands fa-bilibili"
