# 网站基本信息
title: "清绝的导航站"         # 网站标题，显示在浏览器标签页
description: "一个属于我自己的网址导航"  # 网站描述
author: "清绝"             # 作者姓名
logo_text: "我的主页"         # 网站左上角显示的文字

# 个人资料配置 (首页大标题)
profile:
  title: "欢迎来到我的空间"
  subtitle: "这里收藏了我最常用的网站"
  description: "保持探索，保持热爱！"
