name: Build and Deploy Site

on:
  push:
    branches: [ main ]
  workflow_dispatch:
  
# 设置GITHUB_TOKEN的权限
# 我们不再部署到 GitHub Pages，所以可以移除 pages 和 id-token 的写权限
permissions:
  contents: write # 'contents: write' 权限是必需的，因为它需要推送书签的改动

# 允许一个并发部署
concurrency:
  group: "pages"
  cancel-in-progress: true
  
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          persist-credentials: false 
          fetch-depth: 0 
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          
      - name: Install dependencies
        run: npm install
        
      # --- 书签处理步骤 (这部分完整保留) --- 
      - name: Check for bookmark HTML files
        id: check_bookmark_files
        run: |
          if [ -d bookmarks ] && [ "$(find bookmarks -type f -name "*.html" 2>/dev/null)" ]; then
            echo "found=true" >> $GITHUB_OUTPUT
            echo "Bookmark HTML files found, will process them."
          else
            echo "found=false" >> $GITHUB_OUTPUT
            echo "No bookmark HTML files found, skipping bookmark processing."
          fi
        
      - name: Process bookmark files
        if: steps.check_bookmark_files.outputs.found == 'true'
        run: |
          echo "Processing bookmark files..."
          node src/bookmark-processor.js
          
      - name: Debug directory contents
        if: steps.check_bookmark_files.outputs.found == 'true'
        run: |
          echo "Current directory contents:"
          ls -la
          echo "Checking config/user/pages directory:"
          if [ -d config/user/pages ]; then 
            echo "Directory exists, listing contents:"
            ls -la config/user/pages/
            if [ -f config/user/pages/bookmarks.yml ]; then 
              echo "✓ bookmarks.yml exists in config/user/pages/"
              cat config/user/pages/bookmarks.yml | head -n 10
            else 
              echo "✗ bookmarks.yml does not exist in config/user/pages/"
            fi
          else 
            echo "✗ config/user/pages directory does not exist"
          fi
        
      - name: Commit bookmark configuration changes
        if: steps.check_bookmark_files.outputs.found == 'true'
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action (Bookmarks)"
          
          if [ -f config/user/pages/bookmarks.yml ]; then
            if git ls-files --error-unmatch config/user/pages/bookmarks.yml 2>/dev/null; then
              if ! git diff --quiet config/user/pages/bookmarks.yml; then
                git add config/user/pages/bookmarks.yml
                git commit -m "Update bookmarks configuration from imported bookmarks"
              else
                echo "No changes to bookmarks configuration"
              fi
            else
              git add config/user/pages/bookmarks.yml
              git commit -m "Add bookmarks configuration from imported bookmarks"
            fi
            
            if [ -f config/user/navigation.yml ]; then
              if ! git diff --quiet config/user/navigation.yml; then
                git add config/user/navigation.yml
                git commit -m "Update navigation to include bookmarks page"
              fi
            fi
          else
            echo "ERROR: config/user/pages/bookmarks.yml does not exist! Bookmark processing may have failed."
            ls -la config/user/pages/ || echo "Directory does not exist"
          fi
          
      - name: Clean up processed bookmark files
        if: steps.check_bookmark_files.outputs.found == 'true'
        run: |
          HTML_FILES=$(find bookmarks -type f -name "*.html" 2>/dev/null)
          if [ -n "$HTML_FILES" ]; then 
             git config --local user.email "action@github.com"
             git config --local user.name "GitHub Action (Cleanup)"
             FILE_COUNT=$(echo "$HTML_FILES" | wc -l)
             find bookmarks -type f -name "*.html" -delete
             REMAINING=$(find bookmarks -type f -name "*.html" 2>/dev/null)
             if [ -z "$REMAINING" ]; then
               git add bookmarks/
               git commit -m "Clean up processed bookmark files ($FILE_COUNT files removed)"
             else
               echo "WARNING: Some HTML files could not be deleted:"
               echo "$REMAINING"
             fi
          else
             echo "No HTML files found to clean up."
          fi

      - name: Push configuration changes (if any)
        if: steps.check_bookmark_files.outputs.found == 'true'
        run: |
          git push "https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git" HEAD:${{ github.ref_name }}
        env:
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # --- 网站构建步骤 (仅构建，不部署) ---
      - name: Generate site
        run: npm run generate
        
      - name: Check favicon
        run: |
          if [ -f dist/favicon.ico ]; then
            echo "Favicon exists"
            ls -l dist/favicon.ico
          else
            echo "Warning: favicon.ico not found in dist directory"
          fi
        
      # --- 下面这三个步骤已被删除 ---
      # - name: Setup Pages
      #   uses: actions/configure-pages@v4
      #   
      # - name: Upload artifact
      #   uses: actions/upload-pages-artifact@v3
      #   with:
      #     path: 'dist'
      #     
      # - name: Deploy to GitHub Pages
      #   id: deployment
      #   uses: actions/deploy-pages@v4 
